import Head from "next/head";
import Services from "../components/Cards/Services";
import Reviews from "../components/Reviews/Reviews";
import About from "../components/About/About";
import Partners from "../components/Partners/Partners";
import styles from "../styles/Home.module.sass";
import Call from "../components/Call/Call";
import MainHead from "../components/MainHead/MainHead";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHead />
      <About />
      <Partners />
      <Reviews />
      <Call />
      <Services />
    </div>
  );
}
