import Head from "next/head";
import Reviews from "../components/Reviews/Reviews";
import About from "../components/About/About";
import Partners from "../components/Partners/Partners";
import styles from "../styles/Home.module.sass";
<<<<<<< HEAD
import Call from "../components/Call/Call";
=======
import MainHead from "../components/MainHead/MainHead";
>>>>>>> 28b69d89b7da519a155a9c1609f8b58e7bb260f6

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      <About />
      <Partners />
      <Reviews />
      <Call />
=======
      <MainHead />
      {/* <About/> */}
      {/* <Partners/> */}
>>>>>>> 28b69d89b7da519a155a9c1609f8b58e7bb260f6
    </div>
  );
}
